### ISSUE TITLE
load différentiel

### ISSUE THREAD

**Issue by giotta** [giotta/seao#4]
Pour que notre import des données soit différentiel...

idée : 
pas de UPDATE mais seulement INSERT pour les numeroseao inexistants?
faudrait s'assurer que les fichiers d'origine ne sont jamais updatés

idée : 
travailler avec des dates de mise à jour vs dates d'import si dates de mises à jour existent dans données sources (pas sûr)

**Comment by louib** [comment]
ma vision de la chose cest que si on utilise les fichier xml d'origine, on fait seulement loader les fichiers quon a pas deja loadé, donc cest différentiel par defaut.

**Comment by benwah** [comment]
+1 vision

**Comment by louib** [comment]
Done, la commande syncdata parse la page source html pour trouver les fichiers à downloader, download ceux qui ne sont pas deja dans /data , et load ces meme fichiers dans la db local. Le load est donc incremental.

python manage.py syncdata
